services:
  build:
    image: klakegg/hugo:0.111.3
    volumes:
      - ".:/src"
  server:
    image: klakegg/hugo:0.111.3
    command: server -DF --disableFastRender --watch
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"